### ISSUE TITLE
No lockscreen only login screen

### ISSUE THREAD

**Issue by OccultArt** [PFCKrutonium/Windows-10-Login-Background-Changer#197] opened 2015-08-15 10:28 UTC
After locking the computer or on a boot, I do not get the lock screen, it goes directly to the login screen. Can this be fixed?

**Comment by Bryan-Devenish** [comment] 2015-08-15 17:21
IF you followed the fix, what's happening is that on the initial boot it's failing in a sense to load the .exe for the lock screen in time. However when you log in and press Wins + L, to lock your PC. You'll see the lock screen is still there working.

**Comment by darth62969** [comment] 2015-08-18 19:51
i experience this issue as well, i don't think this is high on priories.

**Comment by tetra-fox** [comment] 2015-08-19 15:09
This is not a bug, but a stock feature that comes with Windows 10, in the [KB3081436](https://support.microsoft.com/en-us/kb/3081436) cumulative update.

**Comment by darth62969** [comment] 2015-08-19 16:55
it is a stock feature. OK then i will remove and bug an close it.

**Closed as completed by darth62969** 2015-08-19 16:55 UTC
