### ISSUE TITLE
Does it support for big resolution image? and  I have been got problems about win for that.

### ISSUE THREAD

**Issue by Englbach** [PFCKrutonium/Windows-10-Login-Background-Changer#286] opened 2016-02-20 09:12 UTC
Please make sure these are checked so we can help you! (put an x in the [ ] to check it)
- [ ] I am running Windows 10, from build 10240 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
- [ ] I am running the program as administrator

If you are using the command line, please give us the full traceback (any output that include errors you have), or an image of the traceback.

If you are using the GUI version, please make sure you can check this:
- [ ] I have the setting "Show Windows background picture on the sign-in screen" set to on (it is in Personalization->Lock Screen)

Also, please send a screen shot of any error dialog that may show up for the GUI version.

Finally, please provide any other information that you feel is relevant.

**Comment by emmatyping** [comment] 2016-02-20 15:37
Hi @Englbach . You seem to not have filled out the questions we have. If you file another bug, please do so! Also, to answer your question, very high qualiy images cannot be used due to issues with the language the program is written in. You will have to try another image, or scale down your image. Sorry. (also for the record, dupe of #144

**Closed as completed by emmatyping** 2016-02-20 15:37 UTC
