### ISSUE TITLE
[Solved] Login Screen is Broken - Follow link to find guide.

### ISSUE THREAD

**Issue by Bryan-Devenish** [PFCKrutonium/Windows-10-Login-Background-Changer#173] opened 2015-08-11 17:40 UTC
Click this link here https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186 to find a guide on how to fix multiple issues that you may have.

**Comment by leyyce** [comment] 2015-08-11 19:52
Yeah pls someone upload the a default (working) .pri

**Comment by tetra-fox** [comment] 2015-08-11 22:53
[For first build windows 10](https://files.gitter.im/PFCKrutonium/Windows-10-Login-Background-Changer/GPSW/Windows.UI.Logon.pri)

[for updated windows 10](https://www.dropbox.com/s/w8rsoqkcz66uilq/Windows.UI.Logon.pri.bak?dl=0) (you don't need to sign up, just click the x button and press download)

**Comment by Bryan-Devenish** [comment] 2015-08-11 23:36
I'll let you know if this sorted it out, otherwise i've been informed of another method. I'll keep you lads posted.

**Comment by leyyce** [comment] 2015-08-12 15:43
Can u link me the alternative method please? 
I found a pri yesterday and it's still not working. 
I'm starting to think that my issue is not caused by  the corrupt pri file...

**Comment by Bryan-Devenish** [comment] 2015-08-12 16:52
@iElCapitan Hey man, i'm uploading a fix for any user missing the .bak file now. Check back within the next hour or two.

**Comment by Bryan-Devenish** [comment] 2015-08-12 19:33
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186 Sorry for taking so long. Here it is.

**Comment by darth62969** [comment] 2015-08-18 19:56
going to close this one now i don't see the point of having it open.

**Closed as completed by darth62969** 2015-08-18 19:56 UTC
