### ISSUE TITLE
Thanks for not allowing me enter in my computer

### ISSUE THREAD

**Issue by MarcCeleiro** [PFCKrutonium/Windows-10-Login-Background-Changer#222] opened 2015-08-20 09:15 UTC
Thanks to this damn program, I can not access my account on my ASUS R510J. The program makes the lock screen to move up and down and not allow me access.

Thank you, really :-1:

**Comment by KaleidonKep99** [comment] 2015-08-20 14:29
We already said that this project is still being developed, and can cause some computers to not pass the login screen.

Take a look here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/39
Or here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/186

And read the readme next time! https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/blob/master/README.md

**Comment by tetra-fox** [comment] 2015-08-21 00:51
You don't have to be so arrogant. [Just read the **wiki** for a **solution**.](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

**Comment by darth62969** [comment] 2015-12-03 18:30
i am going to go ahead and assume the issue is fixed and close it, please make sure you read the wiki for fixes for the most common issues.

**Closed as completed by darth62969** 2015-12-03 18:30 UTC
Labels: duplicate, Tech Support
