### ISSUE TITLE
I Can't Get into my computer at all after downloading Windows 10 login background changer

### ISSUE THREAD

**Issue by whitesong** [PFCKrutonium/Windows-10-Login-Background-Changer#266] opened 2015-10-15 04:36 UTC
My computer has gone haywire.  It will not stop blinking and I can't login at all.  What am I to do.  This is a brand new computer.  OMG, I am freaking out!!  HELP!!!

**Comment by emmatyping** [comment] 2015-10-15 04:39
Ok, step 1. Calm down. This happens, we can help you. 

2 Please follow [these directions](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login). 
They should allow you to get back into your computer.

**Comment by whitesong** [comment] 2015-10-15 05:04
I have tried all that.  When I did the holding the start button 3 times that is when the computer kept flashing.  Haven't been able to get a command prompt.

**Comment by whitesong** [comment] 2015-10-15 06:15
OMG--I contacted ASUS and we couldn't even do a system recovery.  We tried power button + F9, that didn't work.  Then we tried the BIOS recovery and that didn't work.  What are your suggestions now?

**Comment by Krutonium** [comment] 2015-10-15 10:12
https://www.youtube.com/watch?v=W_eHZZW1ung

**Comment by darth62969** [comment] 2015-10-15 11:27
you can also try spamming F8 at boot, that should work, it did on older versions of windows. don't think it worked after 8.

you can also try this
http://windows.microsoft.com/en-us/windows-10/change-startup-settings-in-windows-10#v1h=tab02

**Comment by darth62969** [comment] 2015-12-03 18:25
going to close this as it has been over a month since this was commented on. i am going to assume the issue is taken care of, if not feel free to let us know.

**Closed as completed by darth62969** 2015-12-03 18:25 UTC
Labels: duplicate, Tech Support

**Comment by whitesong** [comment] 2015-12-03 20:24
The issue has not been taken care of--I still need HELP.  I have just been copying from emails I sent out already.

Edit(darth62969): removed personal information. be careful next time

**Comment by whitesong** [comment] 2015-12-03 20:26
Sorry, wrong issue.  Yes, I am back in to my computer.  THanks!!

Edit (darth62969): removed personal information be careful next time.

**Comment by darth62969** [comment] 2015-12-03 20:31
nice to know, and i hope that other issue is resolved soon as well.
