### ISSUE TITLE
Doesn't work with Windows' "high contrast" themes

### ISSUE THREAD

**Issue by prestonpdx** [PFCKrutonium/Windows-10-Login-Background-Changer#240] opened 2015-08-30 18:58 UTC
Under Settings > Personalization, Windows 10 offers four high-contrast themes. Your login background changer doesn't seem to work with these, although it works great with the regular themes.

**Comment by emmatyping** [comment] 2015-08-30 19:07
Are you talking about the app, or the program itself? Is it changing the logon screen background?

**Comment by emmatyping** [comment] 2015-08-31 00:33
you could also use the command line version. That won't be affected by the theme.

**Comment by prestonpdx** [comment] 2015-08-31 17:57
Thanks for your help. I'm using the Windows version of the program. I guess you call that the app. The screen I get is plain yellow, not the image I am trying to install nor is it the standard blue window screen that you normally see with Win 10. This yellow screen may be the one that comes with the theme I'm using or your program may have changed it to that (but it didn't change it to the image I want).

I'll try the command line version if I can figure it out. I hope I can find instructions for it somewhere.

**Comment by emmatyping** [comment] 2015-09-01 00:04
It just so happens we have instructions [here](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Command-Line)

**Comment by prestonpdx** [comment] 2015-09-01 04:41
Thanks, but the posted instructions are pretty sketchy for a neophyte 
like me. My command line executable is located in C:\Temp\Command 
Line, and my image, windoze.jpg, is in the root of C:. The attachment 
shows what I tried.

-- Preston

At 05:04 PM 8/31/2015, you wrote:

**Comment by darth62969** [comment] 2015-09-01 14:27
GitHub does not show attachments via email, could you PasteBin it and give us a link

http://pastebin.com/

**Comment by prestonpdx** [comment] 2015-09-01 16:08
I've never heard of PasteBin before. I've now created an account, but 
I see no way to upload my JPG attachment -- it seems to only accept 
text. Can you tell me how to PasteBin a JPG screenshot or is there 
another way to get this 45KB file to you?

-- Preston

At 07:28 AM 9/1/2015, you wrote:

**Comment by darth62969** [comment] 2015-09-01 16:27
If it is a jpeg then use imgur. I was under an assumption it was a text file or something like that. The geek in me thinks of something like a log or something like that. 

(: Jonathan :)

Sent from my Windows Phone

-----Original Message-----

**Comment by prestonpdx** [comment] 2015-09-01 16:48
Here you are: http://imgur.com/SCrEwx7

At 09:27 AM 9/1/2015, you wrote:

**Comment by darth62969** [comment] 2015-09-01 17:02
don't use quotes when you run the program
only the directory.

(: Jonathan :)

**Comment by prestonpdx** [comment] 2015-09-01 18:57
Hi Jonathan,

Thanks for the help,  but I'm still not out of the woods. The 
screenshot illustration on your website seems to have quotes on the 
command. When I use quotes for help (/h), it works (please see the 
new screenshot, http://imgur.com/ERRI0cR  ). But when I do the same 
thing for the image, it doesn't work. Then when I remove the quotes 
from the program, it tells me that W10 is invalid. Am I 
misinterpreting your instructions?

-- Preston

At 10:02 AM 9/1/2015, you wrote:

**Comment by darth62969** [comment] 2015-09-01 19:11
nah i screwed up, and did not get a chance to correct my self. you are correct in the way you are doing it, and @Toyz  is going to fix it, the next pull request should fix this.

also you are not alone on this... trying to figure out what is going on.

**Comment by Toyz** [comment] 2015-09-01 19:12
I know what the issue is and I will fix it when i get home

How System.Args aka 

```
public static void main(string[] args) //how this works
```

String[] args stores all values passed via command line cause you have the "" around the exe name it things that your calling "" as a file name (Still on C# api not ours)

**Comment by darth62969** [comment] 2015-09-01 19:22
settings don't show in high contrast mode. the app works but the settings don't show. 

we need a check for high contrast now.

**Comment by Toyz** [comment] 2015-09-02 03:43
Fixed in commit 8d20a05faebe1aafa3efbbef343bc296c41e7e43

**Closed as completed** 2015-09-02 03:43 UTC
Labels: bug

**Comment by prestonpdx** [comment] 2015-09-02 18:45
I'm sorry but I'm lost. I went to the link below and found something 
to download that looked like a fix. But I couldn't find a command 
line *.exe file in the package.

If I'm supposed to do something now, please be explicit with me.

-- Preston

At 08:43 PM 9/1/2015, you wrote:

**Comment by darth62969** [comment] 2015-09-02 19:37
unless you want to and know how to compile the app, i would wait for a
release. just so you know the app does work in high contrast mode, but the
changes are not shown. you get a black grey or what ever screen for the
logon.

(: Jonathan :)
