### ISSUE TITLE
Black screen error

### ISSUE THREAD

**Issue by Tigger1111** [PFCKrutonium/Windows-10-Login-Background-Changer#56] opened 2015-08-02 07:30 UTC
I've used the oldest version of yours.
There was no problem when just changing pictures or colors but after i unchecked to hidden my user icon, it just appears a black screen and a cursor. 
How can I recover my computer? Nothing works...pls help

**Comment by tetra-fox** [comment] 2015-08-02 16:35
The oldest version is broken. The permissions don't set correctly. (By the way, the hide user icon checkbox does not do anything to the login screen, it is just for the preview in the program.)

To fix this:
1. Obtain a USB installation of Windows 10.
2. Copy [this .pri file](https://files.gitter.im/PFCKrutonium/Windows-10-Login-Background-Changer/GPSW/Windows.UI.Logon.pri) to the root of your USB drive.
3. Boot from the USB drive on your computer.
4. Click on "Repair your computer"
5. Click on Troubleshoot
6. Click on Advanced Options
7. Click on command prompt
8. Type in `echo list volume | diskpart` and find your USB drive's drive letter, and your windows install drive letter
9. Type in `takeown /f \"[windrive]:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri" && icacls \"[windrive]:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri" /grant administrators:F`
   - [windrive] would be your windows install drive letter
10. Type in `del [windrive]:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri`
    - [windrive] would be your windows install drive letter
11. Type in `copy [usbdrive]:\Windows.UI.Logon.pri [windrive]:\Windows\SystemResources\Windows.UI.Logon\`
12. [windrive] would be your windows install drive letter
13. [usbdrive] would be your usb drive letter
14. Reboot into windows and login.
    - Note how I said login :stuck_out_tongue_winking_eye: 
15. [Now use the newest version that _**actually works**_ and doesn't leave you with a 0 byte file!](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/4)

**Comment by tetra-fox** [comment] 2015-08-02 22:32
Also, this is a duplicate of #15.

**Closed as completed** 2015-08-04 22:02 UTC
Labels: duplicate

**Comment by philipshirk** [comment] 2015-08-08 22:08
Tried twice (on clean installs of 10 both times). Got the blinking screen both times. Command prompt solution didn't work (it claimed the file wasn't accessible or didn't exist). I reinstalled windows the first time, used system restore the second time. Now I've given up.

**Comment by Toyz** [comment] 2015-08-08 22:21
Seems like it's not being ran as admin, I will look into this when I get to my pic

**Comment by audreycmoss** [comment] 2015-08-09 00:01
this happened to me, too! is there any way to reset or restore without a usb copy of windows 10? or, alternatively, bypass the login screen completely? keyboard shortcuts aren't working and I'm not sure what to do.

**Comment by Toyz** [comment] 2015-08-09 01:17
@audreycmoss pretty much just keep starting windows and then force shutting down 2 - 3 times and it will make windows think it's crashed and kick you into recovery mode

**Comment by paige729** [comment] 2015-08-09 07:55
It does not work at all! My screen blinks all the time and nothing works! Impossible to access into recovery mode! I impossible to root on the usb key! It is a shame to give this software who breaks your computer! How can I do now? I am not a rich people who can pay for a new computer it is awfull really...

**Comment by tetra-fox** [comment] 2015-08-09 16:02
@paige729 it doesn't always break your login screen, only in some cases. but in my case, it works just fine. you also don't need a new computer. you just need to hold shift and f10 together when you are booting your computer. i'm not rich either, you can fix your computer for free, with the cost of a little bit of patience. [here is how to fix it](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

**Comment by paige729** [comment] 2015-08-09 17:19
I am sorry but as i told you: shift and f10 do not work! Nothing change, the screen always blinks and computer does not root :/

**Comment by tetra-fox** [comment] 2015-08-09 20:22
when are you holding shift+f10

when windows is starting or when the login screen is already there?

**Comment by darth62969** [comment] 2015-08-09 20:35
@paige729 there are many ways to get into recovery mode, one is to power off you pc during boot, and i mean when the windows logo is on screen and the swirly dot things are swirling. after you do this 2 or 3 times you will see "Booting into recovery" under the windows logo, this will change a few times, but when done, you want to click one that says advanced options, not 'reboot' then  you want the middle option and then you want the option that says command prompt. you can pick up the steps for here.

sorry for talking down on you but you seem like you need step by step simple instructions like my mother or grandmother would. also sorry if i came off cross or mean, i did not intend to come off that way.

**Comment by paige729** [comment] 2015-08-10 06:46
Oh yes I am a mother (44) and I am french, so you are perfecty right to speak me like that ! No problem, thank you for this :-)

BUT I tried what you said, and nothing works (I tried with my husband who is "ingenieur" (I do not know the english word sorry)), and when I power in, I don't have the windows logo, I have "acer" and after acer, the screen is blinking now. 

I tried shift f10 (and shift f8 and alt f0 etc etc I did it for 2 days now) during the logo "acer", I tried power off during the logo "acer" but no way: always the screnn is blinking. It is like the computer does not find Windows.... I am desesperate...

Thank you for help me, I am old, french and completely lost....(and sorry for my late response, but it is the jet lag I think...)

**Comment by paige729** [comment] 2015-08-10 06:55
héééééééééééééééé I dis "echap" and power, I had the logo windows and I power off as you said and it is done, I have the screen you talked !!!!!!!!! Ok calm down Paige ;-)

So now what is my "windows drive letter" C? D? and what I have to do with this letter?

oh oh I hope, I hope !! Thank YOUUU !

**Comment by paige729** [comment] 2015-08-10 07:01
I hav to leave my house for one week, I follow this : https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login

but I choose C for windows drive letter But at the line: 5.Type in [win]: je type only C

and it says me "not a good way" or something like that. Can you help me again please? I thank you so much I think I COULD MAYBE ONE  DAY repair it....!

**Comment by paige729** [comment] 2015-08-10 09:27
It is repeared ! !! I  have forgotten to  put : at  the end of the sentence ! !! Thank you so much ! ! I am so happy !

**Comment by mrwilliamhofw** [comment] 2016-08-08 16:51
Hi all!
I need help wih this problem too. I followed the instructions, but when I type in DIR, it shows me that I don't have .pri or .bat file! I know I deleted it, but I also copied it from the USB and after that it's not in the list again! How is that possbile?
Can you please help me fix this problem without reinstalling and loosing everything?
Thank you in forward,
William

**Comment by mrwilliamhofw** [comment] 2016-08-08 16:57
Oh wait, now I have .pri and .pri.BACKUP
can someone answer me ASAP how to fix it??

**Comment by emmatyping** [comment] 2016-08-08 17:43
mrwilliamhofw, please go on our gitter, I can try to help you there.

 https://gitter.im/PFCKrutonium/Windows-10-Login-Background-Changer

**Comment by Dripper2324** [comment] 2019-10-21 15:33
Thankssss. It works for me with steps from paige above,,,, thanks... Now my logon screen back as normal 👍😘
