### ISSUE TITLE
Reset on every new boot

### ISSUE THREAD

**Issue by Bletotum** [PFCKrutonium/Windows-10-Login-Background-Changer#107] opened 2015-08-06 17:22 UTC
Every time windows starts, the logon screen is back to the default.

**Comment by ghost** [comment] 2015-08-07 07:08
Confirmed, same thing here. Probably has to do with the recent update.

**Comment by kurtextrem** [comment] 2015-08-07 07:43
I think the same about the update. It removed my custom background after I applied it.

**Comment by superkev73** [comment] 2015-08-07 14:23
This happened to me after a Windows Update, but after setting my custom background again, it has persisted through several reboots.

**Comment by Toyz** [comment] 2015-08-07 19:10
I'm looking into the issue there's a few new values in the PRI

**Comment by tetra-fox** [comment] 2015-08-07 20:02
This is probably since there's new values in the PRI as @Toyz pointed out. Maybe those values are so that Windows can verify the file was not tampered with, and it can reset to the correct, official version from Microsoft if it was.

**Comment by Toyz** [comment] 2015-08-07 20:14
They look more like new image sizes but I can't confirm 100% yet

**Comment by ghost** [comment] 2015-08-08 08:30
@Syrexide But if they don't want us to change it, why did they make it so ugly?

**Comment by tetra-fox** [comment] 2015-08-08 16:27
@GeoffreyVDB I'm not Microsoft, I don't know.

**Comment by darth62969** [comment] 2015-08-19 14:34
going to close this as it should be fixed in the latest update, create a new issue if this persists.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Closed as completed by darth62969** 2015-08-19 14:34 UTC
