### ISSUE TITLE
Screen flickers after changing background

### ISSUE THREAD

**Issue by siddharthmani** [PFCKrutonium/Windows-10-Login-Background-Changer#106] opened 2015-08-06 15:02 UTC
Hi,

My screen started flashing after changing the background and because of which i m unable to login to my machine!!! Could you please help?

**Comment by ghost** [comment] 2015-08-06 15:47
Yeah me too please guys help!

**Comment by ghost** [comment] 2015-08-06 15:47
Same. I'm getting red flashes. Can't get past the lock screen. Tried to get past it by holding space bar, but it seems to reset the lock screen whenever it flashes red. One time I got past, just to see an exception message pop up, but then it disappeared again.
Edit: Sounds like a similar thing happened over here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/15

**Comment by ghost** [comment] 2015-08-06 15:56
Yeah me too I tried to change the background to a picture and now this happened. Please say that there is something I can do instead of wipe my ssd and hdd.

**Comment by BirkBorkason** [comment] 2015-08-06 16:02
me too, i cant login!! asus f205t (KB3081424)

**Comment by siddharthmani** [comment] 2015-08-06 16:12
i am trying all sorts of things...can someone tell me if i try to remove the password somehow, will i be able to bypass the login screen ? and if so...how to do that? is it possible to change the values back to default from the command prompt which i m able to run using recovery options???

**Comment by ghost** [comment] 2015-08-06 16:15
"PFCKrutonium commented 6 days ago
Next time you have this issue, assuming it happens again, boot up your recovery media, get to a command line, and go to C:\Windows\SystemResources\Windows.UI.Logon. In there, delete the Windows.UI.Logon.pri and replace it with a copy of Windows.UI.Logon.pri.bak"

It sounds like you can fix it by booting in through a Windows 10 recovery disk, and replacing the edited file with the backup.
So, you'd have to download the iso from: https://www.microsoft.com/en-us/software-download/windows10
Burn it to a disk or flash drive.
Boot up your PC and go into the bios. For Asus this would be holding F2 at startup, though the button will depend on your motherboard manufacturer.
Boot into your CD/DVD drive. From here, I think you can enter troubleshoot, then advanced options and reach the command prompt.
Unfortunately, I haven't used command prompt in a while, and won't be able to make a recovery disk until tomorrow, so I can't walk myself, or anyone else, through it. If someone could pick up from me, and help out that'd be great. You'd just have to learn a few options, such as navigating directories and deleting and renaming files: http://www.pcstats.com/articleview.cfm?articleid=1723&page=3

**Comment by ghost** [comment] 2015-08-06 16:20
So if you have to boot to a recovery disk will you lose all your stuff?

**Comment by ghost** [comment] 2015-08-06 16:23
And if I can get to the command prompt without the recovery disc what am I supposed to write into it?

**Comment by siddharthmani** [comment] 2015-08-06 16:29
i have an old machine and its not allowing me to run the mediacreationtool from the link u provided...also my internet is a bit slow..is it possible for u to attach the files which need to be replaced here so that i can download and try what u have mentioned? also let me know the names of the files which need to be edited/replaced?

**Comment by siddharthmani** [comment] 2015-08-06 16:57
never mind...i was able to fix the issue..i was able to boot into a recovery image and navigate to C:\Windows\SystemResources\Windows.UI.Logon (this is where my windows is installed)
there was a backup .pri file present which i renamed to Windows.UI.Logon.pri

Thats it!!

**Comment by ghost** [comment] 2015-08-06 16:58
how did you do that?

**Comment by ghost** [comment] 2015-08-06 16:58
Please help I have no idea how to fix this I am desperste

**Comment by siddharthmani** [comment] 2015-08-06 17:05
as was mentioned...u either need a recovery imageas was mentioned...u either need a recovery image from the link provided or u need to be able to boot from the link provided or u need to be able to boot into recovery via ur existing machine...this is just to get to the command prompt...once u r able to open the command prompt, its easy...just rename the original file to some other name as i had mentioned...and rename the backup to the original name...thats all!!

**Comment by ghost** [comment] 2015-08-06 17:40
ok I could boot to the commsnd prompt onmmy machine but I dont know how to navigate or rename and shit like that

**Comment by ghost** [comment] 2015-08-06 17:46
command prompt = cmd right?

**Comment by Krutonium** [comment] 2015-08-06 18:04
Yep. We will be adding a script to fix this automagically if you can get to a prompt soon :)

**Comment by ghost** [comment] 2015-08-06 18:13
fuck now I might have deleted something and I'm in an infinite boot loop. Well I guess Ill have to boot from a usb disk now. Fuck me I'm dumb.

**Comment by Krutonium** [comment] 2015-08-06 18:16
Don't worry, we all fuck up... I once formatted C: by mistake ;)

**Comment by Toyz** [comment] 2015-08-06 18:17
I once deleted my winboot.efi but i was able to restore it using linux XD

**Comment by ghost** [comment] 2015-08-06 18:32
Does anyone have any tips? I dont even hsve bsckups :|

**Comment by ghost** [comment] 2015-08-06 18:52
No idea about the infinite booting, sorry, but if anyone's command prompt illiterate, I think you can boot into an Ubuntu iso, then just navigate to the right directory through their GUI. They have this test system option, which runs the operating system from the disk. You should be able to access everything on your hard drive. http://www.ubuntu.com/download/desktop/try-ubuntu-before-you-install
Edit: Could try doing a repair with the Windows 10 disk?

**Comment by Krutonium** [comment] 2015-08-06 18:57
Indeed, repairing from a Win10 Disk could work.

**Comment by ghost** [comment] 2015-08-06 19:03
I dont have a win10 disk since I upgraded from win7 witht the free uprgade. And I dont have a win7 disc because I bought OEM key and used an ISO.

**Comment by Krutonium** [comment] 2015-08-06 19:22
https://www.microsoft.com/en-us/software-download/windows10ISO

The Download Tool can download you an ISO to burn to DVD.

**Comment by jeremybasolo** [comment] 2015-08-06 19:43
Ha! Wanted to change that bloody login image, found this repository, didn't look at the comments and just went ahead... Now my screen flickers too. I guess I'm good to create a Windows 10 USB boot and try the command line stuff...

**Comment by Krutonium** [comment] 2015-08-06 19:45
@jeremy We just released an updated version... The hope being it will fix this issue.

**Comment by Krutonium** [comment] 2015-08-06 19:46
Also, going to re-open since this is a very active discussion.

**Comment by jeremybasolo** [comment] 2015-08-06 19:49
Well, if I manage to fix it, I think I'll have learnt how to love the default login image haha ^^

**Comment by ghost** [comment] 2015-08-06 19:59
But can I use the Windows 10 iso if I used the key I bought already

**Comment by Krutonium** [comment] 2015-08-06 20:04
Part of the problem is Microsoft keeps changing stuff plus they keep including a new copy of the files we replace with updates.

**Comment by boylermaker** [comment] 2015-08-06 20:05
I booted using a USB as instructed here: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/issues/56

But the command takeown /f \"[windrive]:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri" && icacls \"[windrive]:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri" /grant administrators:F

Just results in ERROR: File or Directory not found.  My [windrive] was C, at least I assume that is the  "windows install drive letter"--my only choices from the diskpart step were C (Label="OS") and D (Label="ESD-USB").

I cannot manually cd into C:\Windows\SystemResources.  I try, but I just stay in the directory I started from (X:\Sources).

What am I doing wrong?

**Comment by Krutonium** [comment] 2015-08-06 20:12
Try just typing

 C:

**Comment by boylermaker** [comment] 2015-08-06 20:23
That worked!

(For ignorant people like me, you get in to C: by just typing C:, then use "cd SystemResources\Windows.UI.Logon to get to the right folder.  Then "dir" shows you what is there, and I used "copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri to overright the new-and-buggy file with the old one).

Thanks for your help, PFCK!

**Comment by tetra-fox** [comment] 2015-08-06 21:32
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by Keavon** [comment] 2015-08-07 00:38
Thanks for the fix instructions @crusselrow

**Comment by siddharthmani** [comment] 2015-08-07 01:54
if u r able to get to a command prompt after the issue happens, below are the steps (type the commands without using double quotes ("")):
1. By default ur command prompt will show some X: path or something. So type "C:" and press enter.
2. Once you are in C:, type "cd SystemResources\Windows.UI.Logon"
3. U should have reached the above path by now. Once the path is reached, type "dir" and press enter and  you should be able to see the list of files present in that directory. More importantly these 2 files should be present:
 a) Windows.UI.Logon.pri
 b) Windows.UI.Logon.pri.bak
4. If you are able to get to Step 3 then the next is pretty simple. Type below 2 commands (in succession):
 a) "del Windows.UI.Logon.pri"
 b) "ren Windows.UI.Logon.pri.bak Windows.UI.Logon.pri"
5. Thats it!! Exit from Command prompt and reboot your machine, you should be able to get the default login screen back and enter into the Operating system without the flickering issue.

PS - The above commands are given keeping in mind that your Windows is installed on C: or C drive. IF its some other drive, then you need to replace the letter accordingly.

**Comment by Jsexton1119** [comment] 2015-08-07 02:10
I too am having this problem. How exactly can I get windows 10 on a bootable USB? I can't get into my pc at all. I got the free upgrade so I have no disc or installation files at my disposal.

**Comment by siddharthmani** [comment] 2015-08-07 02:16
u have to use someone else's machine just for this purpose...if not, try to get into recovery mode...even i didnt have a bootable usb..but i have a SONY VAIO and it has an option to go into recovery mode by pressing the "ASSIST" button...even though there is no recovery media, it will give u advanced options like opening a command prompt and all..with that u can work ur way!

**Comment by Jsexton1119** [comment] 2015-08-07 02:28
I have an xpress recovery option on mine however I've tried several times and can't get into it either. I have access to another old computer but it doesn't have windows 10 and Windows update doesn't seem to be working so I can't update that machine but is there a way to download the installation files to put on a USB?

**Comment by jeremybasolo** [comment] 2015-08-07 02:43
Finally fixed it! Download the tool from here: https://www.microsoft.com/en-gb/software-download/windows10 and create a USB boot drive. Look up in the conversation for instructions about what to do after.

**Comment by Jsexton1119** [comment] 2015-08-07 04:04
Ok, now I have it on USB but when I go to boot from it my computer gets to the "verifying DMI pool data" and then stops with a flashing cursor under it. Tried to type where the cursor is but it doesn't do anything.

**Comment by chiefulia** [comment] 2015-08-07 05:34
Its not flickering anymore, but i have my lock screen, then press any button and it goes to a blank yellow screen (that was my theme color). I cannot do anything. when I shut down my ASUS holding the power button, then press the power button to turn on again, it automatically goes to the blank yellow screen, I can't boot anything!

**Comment by ctran046** [comment] 2015-08-07 10:44
Does anyone know how to enable a drive using the command prompt? Here's some context:

I tried creating a bootable usb (downloaded the 64-bit windows 10 English iso) using my spare MacBook since I'm having flickering problems with my PC. It's a fairly old mac so I had to do this through the terminal rather than bootcamp. It didn't work - windows just booted after not finding the OS (made sure to put USB on top of the list).

Next, I tried doing it through a dvd. Burned the iso onto a blank dvd. It seemed like it would work this time since I got to the "Press any key to boot" screen, but it didn't work either. Booted like normal to the flickering screen rather than taking me to system recovery menu. 

Finally, I tried disabling my C drive via the BIOS and after a 2-3 minute delay, I was able to get into the system recovery menu. Thing is, since my drive is locked, I can't even reset the computer and I also think that's the reason I can't access any files to rename/replace the .pri file. I put in "dir" after changing the directory to "C:" and it listed the following:  

0 Recovery.txt.
<DIR> Temp
1 File(s) 0 bytes
1 Dir(s) 70,909,952 bytes free

then I tried the same but with the "D:"  directory and it listed what should be in that hard drive. I'm assuming I can't access any files in my C: drive due to it being locked. Thing is, I can't access the command prompt without disabling it so is there any way to enable the C: drive through the command prompt? 

Any help would be appreciated. Thanks.

**Comment by ctran046** [comment] 2015-08-07 12:37
Can't edit. I managed to fix the issue above, renamed the .pri backup after deleting the .pri file, but now I'm taken to a new screen that says I need to repair a boot BCD file or something. I'm looking into it atm but it doesn't help that most solutions require getting to the system recovery menu which I can't get to anymore

**Comment by chiefulia** [comment] 2015-08-07 14:57
How do I boot from a USB? Do I change the boot priority so that it will use the usb first? If so, and it doesn't work, is that because I have the windows 10 file not loaded correctly on my usb? Please help with specifics. I just copied the .exe file to the usb.

**Comment by TheDefiantSpace** [comment] 2015-08-07 16:09
Thank you siddharthmani for solving this issue for me, I REALLY appreciated it.

If this is of any use to someone, I solved this by logging into my windows 7 OS (option before win10 boot)and going to C:\Windows\SystemResources\Windows.UI.Logon, there was a backup .pri file that I renamed to Windows.UI.Logon.pri to fix everything.

**Comment by chiefulia** [comment] 2015-08-07 16:54
I need a step by step for putting the files I need onto my USB and to boot from it.

**Comment by explor202** [comment] 2015-08-07 18:16
Signed up just so I could share how I fixed it. Tried the CMD prompt with USB media but it kept saying the directly didn't exist. So I shut the W10 PC down and connected the C drive to my Cables2Go adapter (http://www.amazon.com/C2G-Cables-30504-Serial-Adapter/dp/B000UO6C5S) and turned it into an external USB drive. Then I connected it to one of my other PC's and navigated to the SystemResources folder and renamed/deleted the appropriate files. Once I was done I reconnected the drive to my W10 PC and booted it up. It did a scan/fix of the drive at first, but then it restarted and let me log in. Hopefully this helps someone else with the same issue. 
PS: Unfortunately running the newest version of Background Changer did not solve the issue on my PC
PPS: And now I see why it won't work. From another source on the web: WARNING... Using any tool to change your Login image (Windows.UI.Logon.pri) from an upgrade to Windows 10 will disable your login and will loop flicker!! 
I upgraded from 7 to 10 so apparently am SOL!

**Comment by akaishiro** [comment] 2015-08-07 18:25
I've manage to boot into my windows 7 through the dual boot option and replaced the .pri file. After that, it worked fine but my login screen disappeared. it completely skipped my login screen and straight into the password screen. Does anyone know how to solve this problem?

**Comment by chiefulia** [comment] 2015-08-07 21:09
I finally got to the cmd. When I get to system resources and try to type Windows.UI.Logon, it says is not recognized as an internal or external command, operable program or batch file. Does this mean it's not in the system resources folder, and if not, where could it be?
EDIT: okay, so it's definitely in the system resources folder, but what do I do to be able to edit the .pri file that it contains?

**Comment by Toyz** [comment] 2015-08-07 21:52
You run 

Del Windows.UI.Logon.pri
Copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri

**Comment by chiefulia** [comment] 2015-08-07 22:53
It says "could not find C:\Windows.UI.Logon.pri". When I try the Del code

**Comment by Jsexton1119** [comment] 2015-08-08 00:46
So far nothings worked for me. I have an external hard drive, could I put the windows 10 iso on that? And if I do, will it erase everything else on the hard drive? All my music and everything is stored on it so I obviously don't want to lose all of that.

**Comment by tetra-fox** [comment] 2015-08-08 01:30
@chiefulia [try method 2](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

**Comment by chiefulia** [comment] 2015-08-08 02:58
@Syrexide it says "the system cannot find the path specified"

**Comment by ctran046** [comment] 2015-08-08 03:02
Try using different letters. The drive my OS was in was F:

**Comment by chiefulia** [comment] 2015-08-08 03:17
@Syrexide the edited version of method 2 finally worked for me. Thank you so so much!!

**Comment by jasen123** [comment] 2015-08-10 00:37
@jeremybasolo  bro i need your help. what did you do to fix this? please.

**Comment by jeremybasolo** [comment] 2015-08-10 06:10
Download the windows 10 tool for usb boot, run it on a computer and its gonna create the  bootable windows 10 usb. Then you need to boot your fucked up computer on it. Then click on repair computer, then troubleshoot, advanced, command line tool. Then follow the instructions in the thread

-----Original Message-----

**Comment by paige729** [comment] 2015-08-10 06:37
It does not work at all for me. The screen is blinking, all the time and the computer does not root. shift f10 or what any you want do not work ! My computer is dead. I tried the usb key with W10 and it does not work, my computer does not boot on it. I am desesperate...all of this for a login screen !!

**Comment by jeremybasolo** [comment] 2015-08-10 06:40
Yeah I know its frustrating... How have you created the usb key?

-----Original Message-----

**Comment by Toyz** [comment] 2015-08-10 06:45
My most recent pr could fix it cause it fixed a conversion big from powershell to C#

**Comment by paige729** [comment] 2015-08-10 09:25
It is repeared for me!!!! Thank you very much !

**Comment by ItsMeeeeh** [comment] 2015-08-10 11:23
The screen started flickering and after pressing buttons to get to a different menu I can't see anything.. Someone help!

**Comment by paige729** [comment] 2015-08-10 12:43
This is what I did: I press escape AND power button at the same time and then I have seen the logo Windows. Then just at this time, I press power off.
I did this 2/3 times, and at least, the computer booted. And I followed this: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login 

Thank you so much to  darth62969 !!

**Comment by Tobey2606** [comment] 2015-08-10 21:01
@  Syrexide: When I go to cd [win]:\Windows\SystemResources\Windows.UI.Logon\ and enter DIR, neither a pri file nor a bak one is available. I tried that with c (which is my Windows drive letter) and also just in case with e my recovery partition. When I try the del code system confirms that the file is not available. Nothing worked, so I am kind of stuck at step 6./7. Do you have any idea how to resolve this issue even w/o that manual?
Thanks.

**Comment by ktbell444** [comment] 2015-08-11 06:15
Here is what I did when in command prompt, you don't require any ISO file or recovery disk if done correctly. The command prompt is in the X: drive for me and I'm going to assume it is for others as well so using the CD command will not work, this causing errors because there is no SystemResources folder in the X: drive. Type this into the command prompt exactly as I do! I will make sure to tell you when to hit enter, so if the line wraps around just know that it is just because of the length of the command line itself.
Substitute C: for whatever drive you have your windows installed on (If you don't know, stick with C:)

First, make sure you have the .pri and .pri.bak files.

Type this into your command prompt exactly as shown:
dir C:\Windows\SystemResources\Windows.UI.Logon\

Now hit enter and see if these two files are present before continuing, one titled Windows UI.Logon.pri and the other titled the same, just with .bak added after the .pri. If you receive an error, make sure you only put one space between the dir command and C:... try again.

If the files are present, type in this command as shown (Be extremely careful with this command! If you hit enter too early you could cause yourself to do more damage to your computer!):

del C:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri

Before you hit enter, make sure you did not type .bak for this command! If you did, remove the .bak before continuing or else you will require a recovery cd! Now hit enter, you should not see any error, if you do, make sure you have put only one space and that is in between the del command and C:... try again.
Now type this in exactly as shown:

ren C:\Windows\SystemResources\Windows.UI.Logon\Windows.UI.Logon.pri.bak Windows.UI.Logon.pri

Before you hit enter, make sure you typed the file name in correctly! Windows will not be able to use the file if it is not the right name!
Hit enter and you should not see any error. If you do, make sure you have a space in between ren and C:... And another space in between the Windows.UI.Logon.pri.bak and Windows.UI.Logon.pri file names and try again.

You can now close out your command prompt and restart if you were able to complete those tasks.

I hope this helps everyone as I tried to be as thorough as possible to help even those with minimal command prompt knowledge.

**Comment by Tobey2606** [comment] 2015-08-11 18:23
@ktbell444 Indeed your description is very precise - thank you very much for the explanation. However, your if-queue is missing an out in case that .pi and.pi.bak files are NOT available. I have checked all drivers (just in case) and as already mentioned none of them contain these files.

My system crashed last Thursday the first time and I was able to restore everything via recovery mode (I was not aware opf the command prompt solution back that time). Once I have downloaded the latest Windows updates yesterday the flickering issue occured again and this time I am not able to recover the system anymore. When I try to do so the system says that no recovery point exists. In addition I cannot find the .pri and .pri.bak in command prompt.

Any idea how to resolve this without installing W10 ISO?
Appreciate your thoughts.
Thanks.

**Comment by ktbell444** [comment] 2015-08-11 19:41
@Tobey2606 The only other things I could think of where you wouldn't require an ISO of Win10 is if you were able to revert back to your previous Windows version before the upgrade. If you do that then it should bring the old windows files still located on your computer and allow you to logon. Then you just have to choose to upgrade to Win10 again.
Another solution might be if I were to send you a copy of my windows login file. I am not sure if that will work but I believe it is worth a try at this point for you since you cannot even use your computer at the moment anyways. You will just have to use command prompt still and have the file on a thumb drive and plugged in. You will have to copy and paste it into the Windows.UI.Logon folder and then unplug your thumb drive and restart your computer. If this is something you would like to try, let me know by sending me your email address and I will attach the file in my reply.

**Comment by ktbell444** [comment] 2015-08-11 21:42
@Tobey2606 Here is a download link to a working Windows.UI.Logon.pri file:

https://www.dropbox.com/s/n9im7br7zxaq4cu/Windows.UI.Logon.pri?dl=0

Put that file onto a thumbdrive and use command prompt to copy and paste the file into the correct folder on your computer. Remember to remove the thumbdrive after you have done that so when you restart your computer it doesn't try to boot into the wrong drive.

**Comment by JotaErR3** [comment] 2015-08-13 00:15
[[[ NO DVD FIX ]]]]... 

1.turn computer on and off twice till system start troubleshoot by itself 

2.go to advance option then command prompt... 

3.type "D:" (Root will be on D:), type "Dir" to make sure 

4.type "cd Windows\SystemResources\Windows.UI.Logon\", 
5.type"copy Windows.UI.Logon.pri.bak Windows.UI.Logon.pri" yes.. 

6.type "exit" 

7.hit continue to w10 .. done!

**Comment by fradd** [comment] 2015-08-18 16:51
My computer was doing this flashing thing, then I kept trying to boot into safe mode, and now it won't really reboot. It just goes to the Lenovo screen for half a second then a blank turquoise (accent color) screen. No more flickering though.
But yeah it's like my computer won't shut down all the way. Even if I hold the power button to turn it off it just seems like it's going to sleep.

Any solutions?

**Comment by ktbell444** [comment] 2015-08-18 17:38
@fradd Are you using a laptop or a desktop?

**Comment by darth62969** [comment] 2015-08-18 20:08
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Closed as completed by darth62969** 2015-08-18 20:08 UTC

**Comment by LewisGz7** [comment] 2015-08-21 22:14
Umm I'm having the flickering screen using the logon thingy I choose to change the logon picture but it keeps flickering is there a way to get into window's recovery mode without USB or disk any help is appreciated.

**Comment by emmatyping** [comment] 2015-08-21 22:30
@LewisGz7 did you use the newest version of the app? Also, please read [this wiki page](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login) for a comprehensive overview

**Comment by LewisGz7** [comment] 2015-08-21 22:39
So I'm resetting my PC at the moment any more steps?

**Comment by LewisGz7** [comment] 2015-08-21 22:41
Or can I just permanently erase the program background logon changer?
