### ISSUE TITLE
Windows Update & this program

### ISSUE THREAD

**Issue by tetra-fox** [PFCKrutonium/Windows-10-Login-Background-Changer#221] opened 2015-08-20 04:19 UTC
After changing the background, and then updating Windows, Windows is not able to complete the updates. It will roll back after the 2nd restart. I'm 99% this has to do with the permissions and Windows Update not being able to write to the file. 1% this has to do with the fact the file was edited.

**Comment by darth62969** [comment] 2015-08-20 18:37
are you able to reproduce the reliably? i can check it later. but not right now.

**Comment by tetra-fox** [comment] 2015-08-21 00:51
yes, i've tried to update about 4 times.

**Comment by emmatyping** [comment] 2015-08-21 16:19
@Syrexide , have you tried different computers?

**Comment by tetra-fox** [comment] 2015-08-21 18:04
yeah on my sister's and parents' laptops

**Comment by emmatyping** [comment] 2015-08-22 15:54
Hm. I see no reason why Win update would not be able to write to the file. Windows-10-Login-Background-Changer doesn't keep a lock on the file, so it couldn't be interfering with Win Update. It is possible that they found the file was edited, but I doubt that they would block updates b/c of that.

In short, I see no reason why this would be caused by the program.

**Comment by darth62969** [comment] 2015-12-03 18:32
i'm going to close this as a part of some cleaning efforts @Syrexide if you still want this open as you are still having issues, please feel free to reopen it or make a new one.

**Closed as completed by darth62969** 2015-12-03 18:32 UTC
