### ISSUE TITLE
Login Screen is Broken

### ISSUE THREAD

**Issue by tektechnician** [PFCKrutonium/Windows-10-Login-Background-Changer#297] opened 2016-05-06 12:12 UTC
Please make sure these are checked so we can help you! (put an x in the [ ] to check it)
- [~ ] I am running Windows 10, from build 10240 to the current build listed working in the README.md [See here](http://www.windowscentral.com/how-check-your-windows-10-build)
- [ x] I am running the program as administrator

If you are using the command line, please give us the full traceback (any output that include errors you have), or an image of the traceback.

If you are using the GUI version, please make sure you can check this:
- [X ] I have the setting "Show Windows background picture on the sign-in screen" set to on (it is in Personalization->Lock Screen)

Also, please send a screen shot of any error dialog that may show up for the GUI version.

Finally, please provide any other information that you feel is relevant.

---

This is somewhat windows 10 build 10240, but it is education version. It completely breaks the logon file. Just wondering, does windows education even support a background natively? I checked with enterprise and home and it works flawlessly. comparing both of them on build 14332 education does not have the option to set the lockscreen as the background as compared to build 14332 enterprise. Also the application does not launch at all in the educational version.
Error Log:
### W10_Logon_BG_Changer Crash

The invocation of the constructor on type 'W10_Logon_BG_Changer.MainWindow' that matches the specified binding constraints threw an exception.
'System.Dynamic.ExpandoObject' does not contain a definition for 'title_dg_disabled'
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

**Comment by emmatyping** [comment] 2016-05-17 00:08
this is a duplicate of #278 please go there for further discussion. I may release a new build today.

**Closed as completed by emmatyping** 2016-05-17 00:08 UTC
Labels: duplicate
